/*
 * Exemplar-Rust
 *
 * An exemplar rust repo with an openapi spec
 *
 * API version: 0.0.1
 * Contact: decline@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	count int
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// CountGet - Returns the number of times this endpoint has been called.
func (s *DefaultApiService) CountGet() (interface{}, error) {
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	s.count = s.count + 1
	return s.count, nil
}

// DogGet - Returns the string \&quot;woof\&quot;.
func (s *DefaultApiService) DogGet() (interface{}, error) {
	return "woof", nil
}
